spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_crm
    username: postgres
    password: iPhone0303
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  messages:
    always-use-message-format: true
  servlet:
    multipart:
      max-file-size: 10MB
server:
  port: 8080

